### ISSUE TITLE
Fails performing upload

### ISSUE THREAD

**Issue by nerdoza** [isthatcentered/dist-to-ftp#1]
I can't track down this error as the dependency seems to be a private repo.  The action has succeeded in creating the proper directory for the upload, but then it fails with the following error:

```
d:\a\_actions\isthatcentered\dist-to-ftp\v1\dist\index.js:12351
                return reentry()
                ^

ReferenceError: reentry is not defined
    at d:\a\_actions\isthatcentered\dist-to-ftp\v1\dist\index.js:12351:17
    at Timeout._onTimeout (d:\a\_actions\isthatcentered\dist-to-ftp\v1\dist\index.js:12380:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by nerdoza** [comment]
From digging in the `dist` bundle it appears that there is potentially a misconfiguration on our FTP server which is causing it to give an IP address that doesn't pass this test, and this catch would potentially catch this error and handle it if the `reentry` function was in scope.

**Comment by nerdoza** [comment]
After doing more digging I realize that this is actually a problem with the underlying `ftp-deploy` library, so I'm closing this issue.

For anyone else that comes across this error, check that your FTP server is returning a valid external IP address when transitioning to passive mode for the file transfer (many configurations default to the internal address).
